// Phase 9 Part 2 — BOARD_SUMMARY renderer: the AI narrative plus a compact
// readiness gauge and a graph-coverage snapshot (counts from the digest).
import React from "react";
import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import type { ComplianceGraphDigest } from "@/server/lib/graphify/complianceGraphBuilder";

const styles = StyleSheet.create({
  page: { flexDirection: "column", backgroundColor: "#FFFFFF", padding: 44, fontFamily: "Helvetica", fontSize: 11, lineHeight: 1.5 },
  header: { marginBottom: 18, paddingBottom: 10, borderBottomWidth: 2, borderBottomColor: "#D97706" },
  title: { fontSize: 22, fontWeight: "bold", color: "#1C1917", marginBottom: 4 },
  subtitle: { fontSize: 11, color: "#78716C" },
  topRow: { flexDirection: "row", justifyContent: "space-between", marginBottom: 16 },
  gaugeBox: { alignItems: "center", width: 130 },
  gaugeScore: { fontSize: 34, fontWeight: "bold", color: "#D97706" },
  gaugeLabel: { fontSize: 9, color: "#78716C" },
  snapshot: { flex: 1, marginLeft: 20 },
  snapRow: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 2 },
  snapKey: { fontSize: 10, color: "#292524" },
  snapVal: { fontSize: 10, color: "#78716C" },
  narrative: { fontSize: 11, color: "#292524", textAlign: "justify" },
  para: { marginBottom: 8 },
  footer: { position: "absolute", bottom: 24, left: 44, right: 44, fontSize: 8, color: "#A8A29E", textAlign: "center", borderTopWidth: 1, borderTopColor: "#E7E5E4", paddingTop: 6 },
});

export function BoardSummaryDocument({
  title,
  organizationName,
  narrative,
  overallReadiness,
  digest,
  generatedAt,
}: {
  title: string;
  organizationName: string;
  narrative: string;
  overallReadiness: number | null;
  digest: ComplianceGraphDigest;
  generatedAt: string;
}) {
  const paragraphs = narrative.split(/\n{2,}/).filter((p) => p.trim().length > 0);
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>{title}</Text>
          <Text style={styles.subtitle}>
            {organizationName} · Board summary · {new Date(generatedAt).toLocaleString()}
          </Text>
        </View>

        <View style={styles.topRow}>
          <View style={styles.gaugeBox}>
            <Text style={styles.gaugeScore}>
              {overallReadiness === null ? "—" : `${overallReadiness}`}
            </Text>
            <Text style={styles.gaugeLabel}>avg readiness / 100</Text>
          </View>
          <View style={styles.snapshot}>
            {(
              [
                ["Frameworks", digest.counts.frameworks],
                ["Controls", digest.counts.controls],
                ["Evidence items", digest.counts.evidence],
                ["Vulnerabilities", digest.counts.vulnerabilities],
                ["Endpoints", digest.counts.endpoints],
              ] as const
            ).map(([k, v]) => (
              <View style={styles.snapRow} key={k}>
                <Text style={styles.snapKey}>{k}</Text>
                <Text style={styles.snapVal}>{v}</Text>
              </View>
            ))}
          </View>
        </View>

        <View>
          {paragraphs.length === 0 ? (
            <Text style={styles.narrative}>No narrative was generated.</Text>
          ) : (
            paragraphs.map((p, i) => (
              <Text key={i} style={[styles.narrative, styles.para]}>
                {p.trim()}
              </Text>
            ))
          )}
        </View>

        <Text style={styles.footer} fixed>
          Generated by Dharma from graph-extracted compliance facts. AI-narrated; verify before external distribution.
        </Text>
      </Page>
    </Document>
  );
}
